Resources:
  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::215928612026:role/amplify-healthywealthy-dev-ba243-authRole
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: Manali7494
                Repo: 2024-capstone-frontend
                Branch: main
                OAuthToken: '{{resolve:ssm:/path/to/github/oauth/token:1}}' # Using SSM parameter store
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: PSU-Frontend
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: Amplify
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                AppId: d1tar7dey1nggt
                BranchName: main